### ISSUE TITLE
German word of the day showing "Undefined" since November 1

### ISSUE THREAD

**Issue by Hauptstadt** [jmwyds/MMM-WordOfTheDay#4]
Hello,

My mirror has been showing "Undefined" as the word of the day since approximately November 1.  Not sure if this is actively being maintained but in case it was I figured I'd write :)

**Comment by KristjanESPERANTO** [comment]
@Hauptstadt How did you switched to German? Please share your config of the module :slightly_smiling_face:

**Comment by Hauptstadt** [comment]
Ope - I have probably found the wrong Github for one of the many WOTD modules, lol, please forgive me!

**Comment by KristjanESPERANTO** [comment]
No problem 🙂  Please close this issue.

**Comment by Hauptstadt** [comment]
I be an idiot
